export interface ILocation {
  destination: string;
  areas: string[];
}

export const locations: ILocation[] = [
  {
    destination: "Cox's Bazar",
    areas: [
      "Cox's Bazar Sea Beach",
      "Kolatoli Beach",
      "Sugandha Beach",
      "Inani Beach",
      "Himchari",
      "Laboni Beach",
      "Marine Drive",
      "Kalatoli Point",
      "Hotel Motel Zone",
      "Ramu",
    ],
  },
  {
    destination: "Sundarban",
    areas: [
      "Khulna City",
      "Mongla Port",
      "Dhangmari Forest Station",
      "Kotka Wildlife Sanctuary",
      "Hiron Point",
      "Sundarbans Gateway",
      "Karamjal Wildlife Centre",
      "Katka Beach",
      "Dublar Char",
      "Shoronkhola",
    ],
  },
  {
    destination: "Sylhet",
    areas: [
      "Sylhet City Center",
      "Moulvibazar Town",
      "Srimangal Town",
      "Ratargul Swamp Forest",
      "Jaflong",
      "Lalakhal",
      "Tea Garden Road",
      "Bichnakandi",
      "Barlekha",
      "Jaintapur",
    ],
  },
  {
    destination: "Saint Martin",
    areas: [
      "Saint Martin's Island Beach",
      "East Beach",
      "West Beach",
      "Shahpori Island",
      "Chera Dwip",
      "Moubon",
      "Fisherman's community",
      "Narikel Jinjira",
      "Coconut Garden",
      "Kakrajan",
    ],
  },
  {
    destination: "Rangamati",
    areas: [
      "Rangamati City Center",
      "Hanging Bridge",
      "Kaptai Lake",
      "Rajban Vihara",
      "Shuvolong",
      "Chakma Rajbari",
      "Shuvolong Waterfall",
      "Tuk Tuk Eco Village",
      "Subholong",
      "Borkol Parjatan",
    ],
  },
  {
    destination: "Bandarban",
    areas: [
      "Bandarban Town",
      "Nilgiri Hill",
      "Boga Lake",
      "Nilachal",
      "Meghla Tourist Complex",
      "Nilgiri Resort",
      "Shoilo Propat",
      "Ruma Bazaar",
      "Nafakhum Waterfall",
      "Sangu River",
    ],
  },
  {
    destination: "Kuakata",
    areas: [
      "Kuakata Sea Beach",
      "Latachapli Beach",
      "Gangamati Reserved Forest",
      "Misripara Buddhist Temple",
      "Lebur Char",
      "Fatrar Char",
      "Kuakata Parjatan",
      "Alipur Beach",
      "Kathaltali Beach",
      "Jhaubon",
    ],
  },
  {
    destination: "Paharpur",
    areas: [
      "Paharpur Buddhist Monastery",
      "Naogaon Town",
      "Mahasthan Garh",
      "Behula Lakshindar Basor Ghar",
      "Jagaddal Vihara",
      "Mohasthangarh Museum",
      "Porshuram Palace",
      "Shalbon Bihar",
      "Bhairab River",
      "Naogaon Parjatan Motel",
    ],
  },
  {
    destination: "Mahasthangarh",
    areas: [
      "Bogra City Center",
      "Mahasthangarh Museum",
      "Govinda Bhita Temple",
      "Vasu Bihar",
      "Mahasthangarh Fort",
      "Mazar of Shah Sultan Balkhi",
      "Shalban Bihar",
      "Rokhia Jame Mosque",
      "Kamalaksha River",
      "Dharmasagar",
    ],
  },
  {
    destination: "Lalbagh Fort",
    areas: [
      "Old Dhaka City Center",
      "Lalbagh Fort Road",
      "Ahsan Manzil",
      "Armenian Church",
      "Star Mosque",
      "Chawk Bazar",
      "Shankhari Bazar",
      "Sadarghat",
      "Khan Mohammad Mridha Mosque",
      "Buriganga River",
    ],
  },
];
